### PR TITLE
porting cwt_morlet to new func

### PR DESCRIPTION
**Pull request by choldgraf**
I think this addresses #21 . I'm using `_compute_tfr` now, which requires 3D input, thus the kind of awkward listing and de-listing of the inputs. That look correct?

### CODE REVIEW

**Comment by choldgraf** [comment]
looks like the failed travis build isn't related to this PR

**Comment by Eric89GXL** [comment]
Can you just remove the Python2.6 build from `.travis.yml`? We don't test it upstream anymore

**Comment by choldgraf** [comment]
in this pr?

**Comment by Eric89GXL** [comment]
Yes please, might as well get everything working here if you have time

**Comment by choldgraf** [comment]
does that work (see amended commit)? There was a note about needing to change something in MNE if we changed the "old version"...but I'm not really "changing" it so much as removing it completely, so we don't need to do anything else, yeah?

**Comment by Eric89GXL** [comment]
It should be okay. We aren't testing as completely as MNE does, but it should be fine.

**Comment by wmvanvliet** [comment]
Are we ready to merge this one?

**Comment by Eric89GXL** [comment]
+1 for merge from my end

**Comment by choldgraf** [comment]
I think so - as long as you guys are happy w/ it. It's just a small change

**Comment by jasmainak** [comment]
I can't import `mne-sandbox` on `master`. Is this the PR which will fix it? @Eric89GXL good to merge?

**Comment by Eric89GXL** [comment]
yes go ahead

**Comment by jasmainak** [comment]
Thanks @choldgraf ! all back to normal now :)

**Pull request merged**
