### PR TITLE
RF:  Lazy import of pyplot

### PR DESCRIPTION
**Pull request by christianbrodbeck**

### CODE REVIEW

**Comment by wmvanvliet** [comment]
why?

**Comment by christianbrodbeck** [comment]
At least on OS X a pyplot import starts some processes that you might not want, visible by a new app symbol appearing in the dock. `mne` also uses lazy import.

**Comment by Eric89GXL** [comment]
It's also good to lazy import so that when running `nosetests` it can set the backend to `agg`

**Comment by agramfort** [comment]
+1

please fix CIs

**Comment by christianbrodbeck** [comment]
The CIs' failure is related to a recent `mne` API change: `ImportError: cannot import name cwt_morlet`...

**Comment by Eric89GXL** [comment]
This one needs a rebase to get the CIs fixed

**Comment by christianbrodbeck** [comment]
CI is fixed, coverage is down because the plotting functions with the lazy imports don't seem to be tested

**Comment by Eric89GXL** [comment]
Thanks @christianbrodbeck

**Pull request merged**
