### PR TITLE
[MRG] FIX:  mne.io._BaseRaw -> BaseRaw

### PR DESCRIPTION
**Pull request by christianbrodbeck**
Renamed in `mne` #3794

### CODE REVIEW

**Comment by Eric89GXL** [comment]
LGTM

**Comment by christianbrodbeck** [comment]
Travis passes now

**Comment by Eric89GXL** [comment]
BTW results of `SensorNoiseSuppression` do not exactly match those from e.g. `NoiseTools`. It might be worth investigating which is better (if they differ meaningfully) for serious use. One difference is that the mne-sandbox version supports `reject` and `flat` out of the box, but I suspect even having those as `None` you might end up with differences.

**Comment by agramfort** [comment]
LGTM merge if done

**Comment by Eric89GXL** [comment]
Thanks @christianbrodbeck

**Pull request merged**
