### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by wmvanvliet**
Make Travis CI do it's thing.

### CODE REVIEW

**Comment by agramfort** [comment]
Did you activate the Travis hook?

**Comment by wmvanvliet** [comment]
Trying to now...

**Comment by wmvanvliet** [comment]
I'm not allowed to add the Travis hook. I'm not an administrator of this repository.

**Comment by dengemann** [comment]
> I'm not allowed to add the Travis hook. I'm not an administrator of this repository.

now you are

**Pull request merged**
