### PR TITLE
FIX dss:  consistent channel selection

### PR DESCRIPTION
**Pull request by christianbrodbeck**
I got a shape mismatch error because `compute_covariance` does channel picking. I think this `.pick_types` call would be equivalent.

cc @drammock

### CODE REVIEW

**Comment by drammock** [comment]
@christianbrodbeck good catch.  I'm dealing with a degraded RAID today, may not get to this for a day or two...  anyone else feel free to step in.

**Comment by Eric89GXL** [comment]
LGTM, +1 for merge but this also needs a rebase

**Comment by Eric89GXL** [comment]
Thanks @christianbrodbeck

**Comment by drammock** [comment]
argh, thanks @Eric89GXL for reviewing this, it fell off my radar.  Sorry.

**Pull request merged**
